--- 
abstract: OO handling of package name transformations
author: Robert 'phaylon' Sedlacek <rs@474.at>
build_requires: 
  FindBin: 0
  Test::More: 0.62
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Data-PackageName
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Inspector: 0
  Moose: 0
  Path::Class::Dir: 0
  Path::Class::File: 0
  Scalar::Util: 0
  namespace::clean: 0.04
version: 0.01
